"""add planning-layer transactional tables

Revision ID: 0ed43046294c
Revises: 9bb187f73430
Create Date: 2025-12-21 12:16:55.526727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed43046294c'
down_revision: Union[str, Sequence[str], None] = '9bb187f73430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('calendar_week_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('load_batch_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_history_id'), 'demand_history', ['id'], unique=False)
    op.create_table('inventory_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('calendar_week_id', sa.Integer(), nullable=False),
    sa.Column('on_hand_qty', sa.Float(), nullable=False),
    sa.Column('in_transit_qty', sa.Float(), nullable=True),
    sa.Column('safety_stock_qty', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_positions_id'), 'inventory_positions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_positions_id'), table_name='inventory_positions')
    op.drop_table('inventory_positions')
    op.drop_index(op.f('ix_demand_history_id'), table_name='demand_history')
    op.drop_table('demand_history')
    # ### end Alembic commands ###
