"""add raw sales and inventory

Revision ID: 9bb187f73430
Revises: 9ee3cb33b7b0
Create Date: 2025-12-21 12:03:52.906842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb187f73430'
down_revision: Union[str, Sequence[str], None] = '9ee3cb33b7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('material_code', sa.String(), nullable=False),
    sa.Column('plant_code', sa.String(), nullable=False),
    sa.Column('stock_category', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('load_batch_id', sa.String(), nullable=False),
    sa.Column('load_ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_inventory_id'), 'raw_inventory', ['id'], unique=False)
    op.create_table('raw_sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('document_number', sa.String(), nullable=False),
    sa.Column('item_number', sa.String(), nullable=False),
    sa.Column('material_code', sa.String(), nullable=False),
    sa.Column('plant_code', sa.String(), nullable=False),
    sa.Column('customer_code', sa.String(), nullable=True),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('order_qty', sa.Float(), nullable=False),
    sa.Column('order_uom', sa.String(), nullable=False),
    sa.Column('order_value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('load_batch_id', sa.String(), nullable=False),
    sa.Column('load_ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_sales_orders_id'), 'raw_sales_orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_sales_orders_id'), table_name='raw_sales_orders')
    op.drop_table('raw_sales_orders')
    op.drop_index(op.f('ix_raw_inventory_id'), table_name='raw_inventory')
    op.drop_table('raw_inventory')
    # ### end Alembic commands ###
